# Server Configuration
server:
  port: 9090

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointmentdb?useSSL=false&serverTimezone=UTC
    username: root
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
